FROM node:20-alpine

WORKDIR /app

# Copiar package.json e instalar dependências
COPY package.json ./
RUN npm install

# Copiar código fonte
COPY . .

EXPOSE 4000

# O comando será sobrescrito pelo docker-compose
CMD ["npm", "run", "dev"]
